# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: API.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tAPI.proto\x12\teog_serve\"O\n\x0bSearchSlice\x12\x12\n\ninput_info\x18\x01 \x01(\t\x12\x1a\n\rsearch_choice\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x10\n\x0e_search_choice\"6\n\x0einfo_to_search\x12$\n\x04info\x18\x03 \x03(\x0b\x32\x16.eog_serve.SearchSlice\"\x1e\n\x07Persona\x12\x13\n\x0bsearch_info\x18\x04 \x01(\t\"5\n\rSearchResults\x12$\n\x08personas\x18\x05 \x03(\x0b\x32\x12.eog_serve.Persona2\xbd\x01\n\x06\x61skEOG\x12\x37\n\x03Get\x12\x16.eog_serve.SearchSlice\x1a\x18.eog_serve.SearchResults\x12;\n\x0bGet_UStream\x12\x16.eog_serve.SearchSlice\x1a\x12.eog_serve.Persona0\x01\x12=\n\x0bGet_BStream\x12\x16.eog_serve.SearchSlice\x1a\x12.eog_serve.Persona(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'API_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_SEARCHSLICE']._serialized_start=24
  _globals['_SEARCHSLICE']._serialized_end=103
  _globals['_INFO_TO_SEARCH']._serialized_start=105
  _globals['_INFO_TO_SEARCH']._serialized_end=159
  _globals['_PERSONA']._serialized_start=161
  _globals['_PERSONA']._serialized_end=191
  _globals['_SEARCHRESULTS']._serialized_start=193
  _globals['_SEARCHRESULTS']._serialized_end=246
  _globals['_ASKEOG']._serialized_start=249
  _globals['_ASKEOG']._serialized_end=438
# @@protoc_insertion_point(module_scope)
